### ISSUE TITLE
Add history functionality

### ISSUE THREAD

**Issue by devSomethingSomething** [devSomethingSomething/help-for-hire-web-api#13]
Need model? Yes
Need controller? Yes
Requires service? Not currently, but it will have to be cleaned up later

**Comment by Minch909** [comment]
Will see what I can do and research a bit

**Comment by Minch909** [comment]
I am done with this. just double check for me please and let me know if I need to change anything

**Comment by devSomethingSomething** [comment]
Will close this issue as you can merge it now.
